site_name: base.essence
site_description: The Base Essence for all Complex Adaptive System Modules in this domain.
site_author: Deepworks
copyright: Deepworks 2025
repo_url: https://github.com/base.essence
extra:
    version: 0.0.1 # Don't Forget to Update this before Publishing!
plugins:
  - search
  - macros
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tracking
        # - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.indexes
        - navigation.top
        - content.code.copy
        - content.tabs
        - content.tabs.link
        - content.code.copy
        - search.suggest
        - search.highlight
        - search.share
    palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black 
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
'nav':
    - 'Home': 'index.md'
    - 'Design': 'design.md'
    - 'About':
        - 'Contributing': 'about/contributing.md'
        - 'Code of Conduct': 'about/code-of-conduct.md'
