name: Build and Publish Documentation
on:
  push:
    branches: 
      - main
jobs:
  update_release_draft:
    uses: deepworks-net/github.actions/.github/workflows/mkdocs-gh-pages.yml@feature/workflow_updates